i18n: R2S ~ R4S, dungeon Korean translation
OverlayPlugin/cactbot pull request #391
Opened 2024-08-27 07:38 UTC by pyeonch

2024-08-27 09:06 UTC, Bing-su requested changes

2024-08-27 09:06 UTC, Bing-su commented on ui/raidboss/data/07-dt/raid/r3s.ts
> +        ko: '봄바리안 봄 넉백 처리방법 설정',
여기에는 Uptime이라는 단어의 의미를 살리는게 좋을 것 같습니다.

Uptime Knockback은 정확한 타이밍에 넉백 방지를 사용한다는 의미 정도로 해석됩니다.

이전에 에덴에서는 이렇게 번역한 적이 있습니다.

https://github.com/OverlayPlugin/cactbot/blob/6e1a8ed9b95cf52bada4ffb37a5057308388f5bc/ui/raidboss/data/05-shb/raid/e8s.ts#L88-L95

2024-08-27 09:06 UTC, Bing-su commented on ui/raidboss/data/07-dt/raid/r3s.ts
> +        ko: '봄바리안 봄 넉백 처리방법 설정',
제가 작업이 자꾸 늦는데 이렇게 작업해주셔서 감사합니다.

2024-08-27 23:59 UTC, pyeonch commented on ui/raidboss/data/07-dt/dungeon/strayborough-deadwalk.ts
> +          ko: '시전중인 인형 피하기',
아! 레이드/토벌전은 제가 직접 텍스트 보고 경험한 위주로 쓰는데, 이건 어림짐작잡았던 것 같습니다.

2024-08-28 00:03 UTC, pyeonch commented on ui/raidboss/data/07-dt/raid/r3s.ts
> +        ko: '봄바리안 봄 넉백 처리방법 설정',
오히려 계속 번역해주셔서 감사할 따름입니다! 도움이 되었으면 좋겠네요~

2024-08-28 01:35 UTC, Bing-su approved these changes

2024-08-28 02:46 UTC, merged